# app-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
spec:
  type: NodePort
  selector:
    app: sample-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30089

