apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-backup-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Size appropriate for your backups