# mongodb-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: default
  labels:
    app: mongodb
stringData:
  mongo-user: qasim-mongouser
  mongo-password: password1-2-6