apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  type: NodePort  # Expose on a NodePort
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017      # Internal port (MongoDB default)
      targetPort: 27017 # Container port
      nodePort: 30088   # External port (30000-32767)

      